---
- name: OVN - Generate PKI certificates (central)
  hosts: all
  order: shuffle
  gather_facts: no
  vars:
    ovn_name: "{{ ovn_name | default('') }}"
    ovn_pki_path: "../data/ovn/{{ ovn_name }}/"
    ovn_roles: "{{ ovn_roles | default([]) }}"
  tasks:
    - name: Create cluster directory
      delegate_to: 127.0.0.1
      file:
        path: "../data/ovn/{{ ovn_name }}"
        mode: 0755
        state: directory
      throttle: 1
      when: '"central" in ovn_roles or "host" in ovn_roles'

    - name: Create CA private key
      delegate_to: 127.0.0.1
      community.crypto.openssl_privatekey:
        path: "{{ ovn_pki_path }}/ca.key"
      register: ca_key
      throttle: 1
      when: '"central" in ovn_roles or "host" in ovn_roles'

    - name: Create CA signing request
      delegate_to: 127.0.0.1
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ ovn_pki_path }}/ca.key"
        common_name: "OVN CA for {{ ovn_name }}"
        use_common_name_for_san: false
        basic_constraints:
          - 'CA:TRUE'
        basic_constraints_critical: true
        key_usage:
          - keyCertSign
        key_usage_critical: true
      register: ca_csr
      when: "ca_key.changed"
      throttle: 1

    - name: Issue CA certificate
      delegate_to: 127.0.0.1
      community.crypto.x509_certificate:
        path: "{{ ovn_pki_path }}/ca.crt"
        csr_content: "{{ ca_csr.csr }}"
        privatekey_path: "{{ ovn_pki_path }}/ca.key"
        provider: selfsigned
      when: "ca_csr.changed"
      throttle: 1

    - name: Create server keys
      delegate_to: 127.0.0.1
      community.crypto.openssl_privatekey:
        path: "{{ ovn_pki_path }}/{{ inventory_hostname }}.key"
      register: cert_key
      when: 'ovn_roles | length > 0'

    - name: Create server signing request
      delegate_to: 127.0.0.1
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ ovn_pki_path }}/{{ inventory_hostname }}.key"
        common_name: "OVN certificate for {{ inventory_hostname }}"
        use_common_name_for_san: false
      register: cert_csr
      when: "cert_key.changed"

    - name: Issue server certificate
      delegate_to: 127.0.0.1
      community.crypto.x509_certificate:
        path: "{{ ovn_pki_path }}/{{ inventory_hostname }}.crt"
        csr_content: "{{ cert_csr.csr }}"
        ownca_path: "{{ ovn_pki_path }}/ca.crt"
        ownca_privatekey_path: "{{ ovn_pki_path }}/ca.key"
        ownca_not_after: "+3650d"
        ownca_not_before: "-1d"
        provider: ownca
      when: "cert_csr.changed"
      throttle: 1

- name: OVN - Add package repository
  hosts: all
  order: shuffle
  gather_facts: yes
  vars:
    ovn_release: "{{ ovn_release | default('distro') }}"
    ovn_roles: "{{ ovn_roles | default([]) }}"
  tasks:
    - name: Create apt keyring path
      file:
        path: /etc/apt/keyrings/
        mode: 0755
        state: directory
      when: 'ovn_roles|length > 0 and ovn_release != "distro"'

    - name: Add PPA GPG key
      copy:
        src: ../files/ovn/ovn-ppa.asc
        dest: /etc/apt/keyrings/ansible-ovn-ppa.asc
      notify: Update apt
      when: 'ovn_roles|length > 0 and ovn_release == "ppa"'

    - name: Get DPKG architecture
      shell: dpkg --print-architecture
      register: dpkg_architecture
      changed_when: false
      check_mode: no
      when: 'ovn_roles|length > 0 and ovn_release != "distro"'

    - name: Add OVN PPA package source
      template:
        src: ../files/ovn/ovn-ppa.sources.tpl
        dest: /etc/apt/sources.list.d/ansible-ovn-ppa.sources
      notify: Update apt
      when: 'ovn_roles|length > 0 and ovn_release == "ppa"'

  handlers:
    - name: Update apt
      apt:
        force_apt_get: yes
        update_cache: yes
        cache_valid_time: 0

- name: OVN - Install packages
  hosts: all
  order: shuffle
  gather_facts: yes
  vars:
    ovn_ip_address: "{{ ovn_ip_address | default(ansible_default_ipv6['address'] | default(ansible_default_ipv4['address'])) }}"
    ovn_name: "{{ ovn_name | default('') }}"
    ovn_release: "{{ ovn_release | default('distro') }}"
    ovn_roles: "{{ ovn_roles | default([]) }}"

    ovn_central_northbound: "{{ lookup('template', '../files/ovn/ovn-central.servers.tpl') | from_yaml | map('regex_replace', '^(.*)$', 'ssl:[\\1]:6641') | join(',') }}"
    ovn_central_southbound: "{{ lookup('template', '../files/ovn/ovn-central.servers.tpl') | from_yaml | map('regex_replace', '^(.*)$', 'ssl:[\\1]:6642') | join(',') }}"
    ovn_ic_northbound: "{{ lookup('template', '../files/ovn/ovn-ic.servers.tpl') | from_yaml | map('regex_replace', '^(.*)$', 'ssl:[\\1]:6645') | join(',') }}"
    ovn_ic_southbound: "{{ lookup('template', '../files/ovn/ovn-ic.servers.tpl') | from_yaml | map('regex_replace', '^(.*)$', 'ssl:[\\1]:6646') | join(',') }}"
  tasks:
    - name: Install the OVN central package
      apt:
        name:
          - ovn-central
        install_recommends: no
        state: present
      when: '"central" in ovn_roles'

    - name: Install the OVN IC database package
      apt:
        name:
          - ovn-ic-db
        install_recommends: no
        state: present
      when: '"ic-db" in ovn_roles'

    - name: Install the OVN IC package
      apt:
        name:
          - ovn-ic
        install_recommends: no
        state: present
      when: '"ic" in ovn_roles'

    - name: Install the OVN host package
      apt:
        name:
          - ovn-host
        install_recommends: no
        state: present
      notify:
        - Configure OVS
        - Enable OVN IC gateway
      when: '"host" in ovn_roles'

  handlers:
    - name: Configure OVS
      shell: ovs-vsctl set open_vswitch . external_ids:ovn-remote={{ ovn_central_southbound }} external_ids:ovn-encap-type=geneve external_ids:ovn-encap-ip={{ ovn_ip_address }}

    - name: Enable OVN IC gateway
      shell:
        cmd: "ovs-vsctl set open_vswitch . external_ids:ovn-is-interconn=true"
      when: '"ic-gateway" in ovn_roles'

- name: OVN - Set up daemon configuration
  hosts: all
  order: shuffle
  gather_facts: yes
  vars:
    ovn_ip_address: "{{ ovn_ip_address | default(ansible_default_ipv6['address'] | default(ansible_default_ipv4['address'])) }}"
    ovn_az_name: "{{ ovn_az_name | default('') }}"
    ovn_name: "{{ ovn_name | default('') }}"
    ovn_roles: "{{ ovn_roles | default([]) }}"

    ovn_central_northbound: "{{ lookup('template', '../files/ovn/ovn-central.servers.tpl') | from_yaml | map('regex_replace', '^(.*)$', 'ssl:[\\1]:6641') | join(',') }}"
    ovn_central_southbound: "{{ lookup('template', '../files/ovn/ovn-central.servers.tpl') | from_yaml | map('regex_replace', '^(.*)$', 'ssl:[\\1]:6642') | join(',') }}"
    ovn_ic_northbound: "{{ lookup('template', '../files/ovn/ovn-ic.servers.tpl') | from_yaml | map('regex_replace', '^(.*)$', 'ssl:[\\1]:6645') | join(',') }}"
    ovn_ic_southbound: "{{ lookup('template', '../files/ovn/ovn-ic.servers.tpl') | from_yaml | map('regex_replace', '^(.*)$', 'ssl:[\\1]:6646') | join(',') }}"
    ovn_pki_path: "../data/ovn/{{ ovn_name }}/"
  tasks:
    - name: Create OVN config directory
      file:
        path: /etc/ovn
        mode: 0755
        state: directory
      when: 'ovn_roles | length > 0'

    - name: Transfer OVN CA certificate
      copy:
        src: "{{ ovn_pki_path }}/ca.crt"
        dest: /etc/ovn/{{ ovn_name }}.ca.crt
        mode: 0644
      when: 'ovn_roles | length > 0'

    - name: Transfer OVN server certificate
      copy:
        src: "{{ ovn_pki_path }}/{{ inventory_hostname }}.crt"
        dest: /etc/ovn/{{ ovn_name }}.server.crt
        mode: 0644
      when: 'ovn_roles | length > 0'

    - name: Transfer OVN server key
      copy:
        src: "{{ ovn_pki_path }}/{{ inventory_hostname }}.key"
        dest: /etc/ovn/{{ ovn_name }}.server.key
        mode: 0600
      when: 'ovn_roles | length > 0'
      notify:
        - Configure OVN central northbound DB for SSL (certs)
        - Configure OVN central northbound DB for SSL (ports)
        - Configure OVN central southbound DB for SSL (certs)
        - Configure OVN central southbound DB for SSL (ports)
        - Configure OVN IC northbound DB for SSL (certs)
        - Configure OVN IC northbound DB for SSL (ports)
        - Configure OVN IC southbound DB for SSL (certs)
        - Configure OVN IC southbound DB for SSL (ports)

    - name: Configure OVN central database
      template:
        src: ../files/ovn/ovn-central.tpl
        dest: /etc/default/ovn-central
      notify:
        - Restart OVN central
        - Configure OVN AZ name
        - Enable OVN IC route sharing
      when: '"central" in ovn_roles'

    - name: Configure OVN host
      template:
        src: ../files/ovn/ovn-host.tpl
        dest: /etc/default/ovn-host
      notify:
        - Restart OVN host
      when: '"host" in ovn_roles'

    - name: Create OVN IC override directory
      file:
        path: /etc/systemd/system/ovn-ic.service.d
        mode: 0755
        state: directory
      when: '"ic" in ovn_roles'

    - name: Transfer OVN IC override
      copy:
        content: |
          [Service]
          EnvironmentFile=-/etc/default/ovn-ic
          ExecStart=
          ExecStart=/usr/share/ovn/scripts/ovn-ctl start_ic --no-monitor $OVN_CTL_OPTS
        dest: /etc/systemd/system/ovn-ic.service.d/ansible.conf
      notify: Restart OVN IC
      when: '"ic" in ovn_roles'

    - name: Configure OVN IC database
      template:
        src: ../files/ovn/ovn-ic.tpl
        dest: /etc/default/ovn-ic
      notify:
        - Restart OVN IC databases
        - Restart OVN IC
      when: '"ic" in ovn_roles or "ic-db" in ovn_roles'

    - name: Transfer OVN aliases
      template:
        src: ../files/ovn/alias.sh.tpl
        dest: /etc/ovn/alias.sh
      when: 'ovn_roles | length > 0'
  handlers:
    - name: Configure OVN central northbound DB for SSL (certs)
      shell:
        cmd: "ovn-nbctl set-ssl /etc/ovn/{{ ovn_name }}.server.key /etc/ovn/{{ ovn_name }}.server.crt /etc/ovn/{{ ovn_name }}.ca.crt"
      when: '"central" in ovn_roles'

    - name: Configure OVN central northbound DB for SSL (ports)
      shell:
        cmd: "ovn-nbctl set-connection pssl:6641:[::]"
      when: '"central" in ovn_roles'

    - name: Configure OVN central southbound DB for SSL (certs)
      shell:
        cmd: "ovn-sbctl set-ssl /etc/ovn/{{ ovn_name }}.server.key /etc/ovn/{{ ovn_name }}.server.crt /etc/ovn/{{ ovn_name }}.ca.crt"
      when: '"central" in ovn_roles'

    - name: Configure OVN central southbound DB for SSL (ports)
      shell:
        cmd: "ovn-sbctl set-connection pssl:6642:[::]"
      when: '"central" in ovn_roles'

    - name: Configure OVN IC northbound DB for SSL (certs)
      shell:
        cmd: "ovn-ic-nbctl set-ssl /etc/ovn/{{ ovn_name }}.server.key /etc/ovn/{{ ovn_name }}.server.crt /etc/ovn/{{ ovn_name }}.ca.crt"
      when: '"ic-db" in ovn_roles'

    - name: Configure OVN IC northbound DB for SSL (ports)
      shell:
        cmd: "ovn-ic-nbctl set-connection pssl:6645:[::]"
      when: '"ic-db" in ovn_roles'

    - name: Configure OVN IC southbound DB for SSL (certs)
      shell:
        cmd: "ovn-ic-sbctl set-ssl /etc/ovn/{{ ovn_name }}.server.key /etc/ovn/{{ ovn_name }}.server.crt /etc/ovn/{{ ovn_name }}.ca.crt"
      when: '"ic-db" in ovn_roles'

    - name: Configure OVN IC southbound DB for SSL (ports)
      shell:
        cmd: "ovn-ic-sbctl set-connection pssl:6646:[::]"
      when: '"ic-db" in ovn_roles'

    - name: Restart OVN central
      systemd:
        name: ovn-central.service
        state: restarted

    - name: Restart OVN host
      systemd:
        name: ovn-host.service
        state: restarted

    - name: Restart OVN IC
      systemd:
        daemon_reload: true
        name: ovn-ic.service
        state: restarted
      when: '"ic" in ovn_roles'

    - name: Restart OVN IC databases
      systemd:
        name: ovn-ic-db.service
        state: restarted
      when: '"ic-db" in ovn_roles'

    - name: Configure OVN AZ name
      shell:
        cmd: "ovn-nbctl --db={{ ovn_central_northbound }} -c /etc/ovn/{{ ovn_name }}.server.crt -p /etc/ovn/{{ ovn_name }}.server.key -C /etc/ovn/{{ ovn_name }}.ca.crt set NB_Global . name={{ ovn_az_name }}"
      when: '"central" in ovn_roles and ovn_az_name'

    - name: Enable OVN IC route sharing
      shell:
        cmd: "ovn-nbctl --db={{ ovn_central_northbound }} -c /etc/ovn/{{ ovn_name }}.server.crt -p /etc/ovn/{{ ovn_name }}.server.key -C /etc/ovn/{{ ovn_name }}.ca.crt set NB_Global . options:ic-route-adv=true options:ic-route-learn=true"
      when: '"central" in ovn_roles and ovn_az_name'
