---
ovn_clients: "{{ ovn_clients | default([]) }}"
ovn_name: "{{ ovn_name | default('') }}"
ovn_roles: "{{ ovn_roles | default([]) }}"
ovn_release: "{{ ovn_release | default('distro') }}"
ovn_ip_address: "{{ ansible_default_ipv6['address'] | default(ansible_default_ipv4['address']) }}"
ovn_az_name: "{{ ovn_az_name | default('') }}"
