---
# - name: Incus - Add package repository
    - name: Create apt keyring path
      file:
        path: /etc/apt/keyrings/
        mode: 0755
        state: directory
      when: 'incus_roles|length > 0 and incus_release != "distro"'

    - name: Add Zabbly repository key
      copy:
        src: ../files/incus/zabbly.asc
        dest: /etc/apt/keyrings/ansible-zabbly.asc
      notify: Update apt
      when: 'incus_roles|length > 0 and incus_release != "distro"'

    - name: Get DPKG architecture
      shell: dpkg --print-architecture
      register: dpkg_architecture
      changed_when: false
      check_mode: no
      when: 'incus_roles|length > 0 and incus_release != "distro"'

    - name: Add Zabbly package source
      template:
        src: ../files/incus/incus.sources.tpl
        dest: /etc/apt/sources.list.d/ansible-zabbly-incus-{{ incus_release }}.sources
      notify: Update apt
      when: 'incus_roles|length > 0 and incus_release != "distro"'

    - name: Update apt
      apt:
        force_apt_get: yes
        update_cache: yes
        cache_valid_time: 0

# - name: Incus - Install packages and bootstrap
    - name: Install the Incus package
      apt:
        name:
          - incus
        install_recommends: no
        state: present
      register: install
      when: 'incus_roles | length > 0'

    - name: Install the Incus UI package
      apt:
        name:
          - incus-ui-canonical
        install_recommends: no
        state: present
      when: '"ui" in incus_roles'

    - name: Install btrfs tools
      apt:
        name:
          - btrfs-progs
        install_recommends: no
        state: present
      when: "incus_roles | length > 0 and 'btrfs' in incus_init['storage'] | dict2items | json_query('[].value.driver')"

    - name: Install ceph tools
      apt:
        name:
          - ceph-common
        install_recommends: no
        state: present
      when: "incus_roles | length > 0 and 'ceph' in incus_init['storage'] | dict2items | json_query('[].value.driver')"

    - name: Install LVM tools
      apt:
        name:
          - lvm2
        install_recommends: no
        state: present
      when: "incus_roles | length > 0 and 'lvm' in incus_init['storage'] | dict2items | json_query('[].value.driver')"

    - name: Install ZFS tools
      apt:
        name:
          - zfsutils-linux
        install_recommends: no
        state: present
      when: "incus_roles | length > 0 and 'zfs' in incus_init['storage'] | dict2items | json_query('[].value.driver')"

    - name: Set client listen address
      shell:
        cmd: "incus --force-local config set core.https_address {{ incus_ip_address }}"
      when: 'install.changed and ("standalone" in incus_roles or ("cluster" in incus_roles and incus_servers[0] == inventory_hostname))'

    - name: Set cluster listen address
      shell:
        cmd: "incus --force-local config set cluster.https_address {{ incus_ip_address }}"
      when: 'install.changed and "cluster" in incus_roles and incus_servers[0] == inventory_hostname'

    - name: Set OVN NorthBound database
      shell:
        cmd: "incus --force-local config set network.ovn.northbound_connection={{ incus_ovn_northbound }} network.ovn.client_cert=\"{{ lookup('file', '../data/ovn/'+ovn_name+'/'+inventory_hostname+'.crt') }}\" network.ovn.client_key=\"{{ lookup('file', '../data/ovn/'+ovn_name+'/'+inventory_hostname+'.key') }}\" network.ovn.ca_cert=\"{{ lookup('file', '../data/ovn/'+ovn_name+'/ca.crt') }}\""
      notify: Restart Incus
      when: 'install.changed and incus_ovn_northbound and ("standalone" in incus_roles or "cluster" in incus_roles)'

    - name: Add networks
      shell:
        cmd: "incus network create {{ item.key }} --type={{ item.value.type }}{% for k in item.value.local_config | default([]) %} {{ k }}={{ item.value.local_config[k] }}{% endfor %}{% for k in item.value.config | default([]) %} {{ k }}={{ item.value.config[k] }}{% endfor %}"
      loop: "{{ incus_init['network'] | dict2items }}"
      when: 'install.changed and ("standalone" in incus_roles or ("cluster" in incus_roles and incus_servers[0] == inventory_hostname))'

    - name: Add storage pools
      shell:
        cmd: "incus storage create {{ item.key }} {{ item.value.driver }}{% for k in item.value.local_config | default([]) %} {{ k }}={{ item.value.local_config[k] }}{% endfor %}{% for k in item.value.config | default([]) %} {{ k }}={{ item.value.config[k] }}{% endfor %}"
      loop: "{{ incus_init['storage'] | dict2items }}"
      when: 'install.changed and ("standalone" in incus_roles or ("cluster" in incus_roles and incus_servers[0] == inventory_hostname))'

    - name: Add storage pool to default profile
      shell:
        cmd: "incus profile device add default root disk path=/ pool={{ item }}"
      loop: "{{ incus_init['storage'] | dict2items | json_query('[?value.default].key') }}"
      when: 'install.changed and ("standalone" in incus_roles or ("cluster" in incus_roles and incus_servers[0] == inventory_hostname))'

    - name: Add network to default profile
      shell:
        cmd: "incus profile device add default eth0 nic network={{ item }} name=eth0"
      loop: "{{ incus_init['network'] | dict2items | json_query('[?value.default].key') }}"
      when: 'install.changed and ("standalone" in incus_roles or ("cluster" in incus_roles and incus_servers[0] == inventory_hostname))'

    - name: Bootstrap the cluster
      shell:
        cmd: "incus --force-local cluster enable {{ inventory_hostname }}"
      when: 'install.changed and "cluster" in incus_roles and incus_servers[0] == inventory_hostname'

    - name: Create join tokens
      delegate_to: "{{ incus_servers[0] }}"
      shell:
        cmd: "incus --force-local --quiet cluster add {{ inventory_hostname }}"
      register: cluster_add
      when: 'install.changed and "cluster" in incus_roles and incus_servers[0] != inventory_hostname'

    - name: Join the cluster
      throttle: 1
      shell:
        cmd: "incus --force-local admin init --preseed"
        stdin: |-
          cluster:
            enabled: true
            cluster_address: "{{ incus_ip_address }}"
            cluster_token: "{{ cluster_add.stdout }}"
            server_address: "{{ incus_ip_address }}"
            member_config:{% for pool in incus_init.storage %}{% for key in incus_init.storage[pool].local_config | default([]) %}

              - entity: storage-pool
                name: {{ pool }}
                key: {{ key }}
                value: {{ incus_init.storage[pool].local_config[key] }}{% endfor %}{% endfor %}{% for network in incus_init.network %}{% for key in incus_init.network[network].local_config | default([]) %}

              - entity: network
                name: {{ network }}
                key: {{ key }}
                value: {{ incus_init.network[network].local_config[key] }}{% endfor %}{% endfor %}
      when: 'cluster_add.changed'
